### ISSUE TITLE
Deku Scrubs Missing

### ISSUE THREAD

**Issue by ThomasJRyan** [Mego/oot-plando#3]
There seems to be several deku scrub item locations missing including:

**Lost Woods**
2 Scrubs by the sacred forest meadow under a boulder
Either the scrub under the bridge or one of the ones above the forest stage

**Sacred Forest Meadow**
Two scrubs in a grotto by the entrance to the forest temple

**Zora's River**
Two scrubs in a grotto near the start of the river

**Jabu Jabu's Belly**
Scrub below the elevator past the water

**Goron City**
Three scrubs in grotto past some lava

**Dodongo's Cavern**
Lobby scrub
One scrub near the room with the dodongos and torches
Two scrubs near the bomb bag

**Death Mountain Crater**
Three scrubs in a grotto block by a boulder

**Gannon's Castle**
Four scrubs under bridge

**Lake Hylia**
Three scrubs under gravestone

**Gerudo Valley**
Two scrubs in grotto behind tent

**Desert Colossus**
Two scrubs under silver boulder

**Comment by Mego** [comment]
That's probably because I was basing it off of a seed without scrubsanity on. I need to add these scrubs, plus shops for shopsanity, cows for cowsanity, and _shudder_ skulltulas for tokensanity.
